apiVersion: v1
kind: Pod
metadata:
  name: microservice-dotnet-app
  labels:
    app: microservice-aks7
    component: microservice-app7
spec:
 containers:
   - image: microserviceaks.azurecr.io/microservice7:latest
     name: microservice-webapi
     ports:
       - containerPort: 80