apiVersion: v1
kind: Service
metadata:
  labels:
    app: microservice-aks7
  name: microservice-aks7
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 80
  selector:
    app: microservice-aks7
    component: microservice-app7
  type: LoadBalancer